# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitRepoURL',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
