# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='historyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='app.HistoryItem'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='historyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='app.HistoryItem'),
        ),
        migrations.AlterField(
            model_name='issuechange',
            name='historyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='app.HistoryItem'),
        ),
    ]
