# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleonproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.Project'),
        ),
        migrations.AlterField(
            model_name='roleonproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleOnProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
