# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170312_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='donePercentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timeSpent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
