# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170309_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('default', 'silver'), ('primary', 'blue'), ('success', 'green'), ('info', 'light blue'), ('warning', 'yellow'), ('danger', 'red')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('default', 'silver'), ('primary', 'blue'), ('success', 'green'), ('info', 'light blue'), ('warning', 'yellow'), ('danger', 'red')], default='default', max_length=20),
        ),
    ]
