# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_gitrepourl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gitRepoURL',
            new_name='git',
        ),
    ]
